public enum OutdatedCommand {
    ADDCLASS,
    DELETECLASS,
    RENAMECLASS,
    ADDRELATIONSHIP,
    DELETERELATIONSHIP,
    ADDATTRIBUTE,
    DELETEATTRIBUTE,
    RENAMEATTRIBUTE,
    SAVE,
    LOAD,
    LISTCLASSES,
    LISTCLASS,
    LISTRELATIONSHIPS,
    HELP,
    EXIT
}
