# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Generate Coverage Report

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Setup GH Config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - name: Pull dev
      run: |
        git checkout develop
        git pull origin develop
    - name: Switch to feature branch
      run: |
        export BRANCH_NAME="coverage-$(date +%s)"
        git checkout -b $BRANCH_NAME
    - name: Build project
      run: |
        mvn package
    - name: Create Coverage Report
      run: |
        rm -rf ./coverage_report/
        mvn jacoco:report
        mv ./target/site/jacoco ./coverage_report
    - name: Commit Coverage Report
      run: |
        git add .
        git commit -m "Generate JaCoCo Coverage Report"
      continue-on-error: true
    - name: Push Feature Branch
      run: |
        git push origin HEAD
    - name: Merge into develop
      run: |
        git checkout develop
        git pull origin develop
        git merge --no-ff $BRANCH_NAME -m "Merge Coverage Branch $BRANCH_NAME"
        git push origin develop